# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_ReductionSetup.ui'
#
# Created: Thu Feb 19 15:24:07 2015
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(913, 1046)
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(2)
        self.horizontalLayout_9.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.line_6 = QtGui.QFrame(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_6.sizePolicy().hasHeightForWidth())
        self.line_6.setSizePolicy(sizePolicy)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.horizontalLayout_9.addWidget(self.line_6)
        self.label_5 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_9.addWidget(self.label_5)
        self.line = QtGui.QFrame(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_9.addWidget(self.line)
        self.gridLayout.addLayout(self.horizontalLayout_9, 6, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout.addItem(spacerItem, 5, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.tab_calibSetup = QtGui.QTabWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_calibSetup.sizePolicy().hasHeightForWidth())
        self.tab_calibSetup.setSizePolicy(sizePolicy)
        self.tab_calibSetup.setObjectName(_fromUtf8("tab_calibSetup"))
        self.tab_advsetup = QtGui.QWidget()
        self.tab_advsetup.setObjectName(_fromUtf8("tab_advsetup"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_advsetup)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_8 = QtGui.QLabel(self.tab_advsetup)
        self.label_8.setEnabled(False)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_4.addWidget(self.label_8, 2, 0, 1, 1)
        self.pushButton_timeFocusTableFile = QtGui.QPushButton(self.tab_advsetup)
        self.pushButton_timeFocusTableFile.setObjectName(_fromUtf8("pushButton_timeFocusTableFile"))
        self.gridLayout_4.addWidget(self.pushButton_timeFocusTableFile, 0, 3, 1, 1)
        self.lineEdit_16 = QtGui.QLineEdit(self.tab_advsetup)
        self.lineEdit_16.setEnabled(False)
        self.lineEdit_16.setObjectName(_fromUtf8("lineEdit_16"))
        self.gridLayout_4.addWidget(self.lineEdit_16, 3, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.tab_advsetup)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_4.addWidget(self.label_7, 1, 0, 1, 1)
        self.lineEdit_timeFocusTable = QtGui.QLineEdit(self.tab_advsetup)
        self.lineEdit_timeFocusTable.setObjectName(_fromUtf8("lineEdit_timeFocusTable"))
        self.gridLayout_4.addWidget(self.lineEdit_timeFocusTable, 0, 1, 1, 2)
        self.label_22 = QtGui.QLabel(self.tab_advsetup)
        self.label_22.setEnabled(False)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_4.addWidget(self.label_22, 3, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.tab_advsetup)
        self.label_9.setEnabled(False)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_4.addWidget(self.label_9, 3, 2, 1, 1)
        self.lineEdit_vanDBFile = QtGui.QLineEdit(self.tab_advsetup)
        self.lineEdit_vanDBFile.setObjectName(_fromUtf8("lineEdit_vanDBFile"))
        self.gridLayout_4.addWidget(self.lineEdit_vanDBFile, 1, 1, 1, 2)
        self.lineEdit_5 = QtGui.QLineEdit(self.tab_advsetup)
        self.lineEdit_5.setEnabled(False)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.gridLayout_4.addWidget(self.lineEdit_5, 3, 3, 1, 2)
        self.checkBox_autoVanRun = QtGui.QCheckBox(self.tab_advsetup)
        self.checkBox_autoVanRun.setObjectName(_fromUtf8("checkBox_autoVanRun"))
        self.gridLayout_4.addWidget(self.checkBox_autoVanRun, 1, 4, 1, 1)
        self.pushButton_vanDBFile = QtGui.QPushButton(self.tab_advsetup)
        self.pushButton_vanDBFile.setObjectName(_fromUtf8("pushButton_vanDBFile"))
        self.gridLayout_4.addWidget(self.pushButton_vanDBFile, 1, 3, 1, 1)
        self.label_10 = QtGui.QLabel(self.tab_advsetup)
        self.label_10.setEnabled(False)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_4.addWidget(self.label_10, 2, 2, 1, 2)
        self.lineEdit_6 = QtGui.QLineEdit(self.tab_advsetup)
        self.lineEdit_6.setEnabled(False)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.gridLayout_4.addWidget(self.lineEdit_6, 2, 4, 1, 1)
        self.label_6 = QtGui.QLabel(self.tab_advsetup)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_4.addWidget(self.label_6, 0, 0, 1, 1)
        self.lineEdit_4 = QtGui.QLineEdit(self.tab_advsetup)
        self.lineEdit_4.setEnabled(False)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.gridLayout_4.addWidget(self.lineEdit_4, 2, 1, 1, 1)
        self.pushButton_vanDBCriteriaSetup = QtGui.QPushButton(self.tab_advsetup)
        self.pushButton_vanDBCriteriaSetup.setObjectName(_fromUtf8("pushButton_vanDBCriteriaSetup"))
        self.gridLayout_4.addWidget(self.pushButton_vanDBCriteriaSetup, 1, 5, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 0, 5, 1, 1)
        self.tab_calibSetup.addTab(self.tab_advsetup, _fromUtf8(""))
        self.tab_generalsetup = QtGui.QWidget()
        self.tab_generalsetup.setObjectName(_fromUtf8("tab_generalsetup"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab_generalsetup)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.gridLayout_2.addLayout(self.horizontalLayout_8, 2, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_11 = QtGui.QLabel(self.tab_generalsetup)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_6.addWidget(self.label_11)
        self.lineEdit_binsize = QtGui.QLineEdit(self.tab_generalsetup)
        self.lineEdit_binsize.setObjectName(_fromUtf8("lineEdit_binsize"))
        self.horizontalLayout_6.addWidget(self.lineEdit_binsize)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.checkBox_sumRuns = QtGui.QCheckBox(self.tab_generalsetup)
        self.checkBox_sumRuns.setObjectName(_fromUtf8("checkBox_sumRuns"))
        self.horizontalLayout_6.addWidget(self.checkBox_sumRuns)
        self.checkBox_filterBadPulses = QtGui.QCheckBox(self.tab_generalsetup)
        self.checkBox_filterBadPulses.setObjectName(_fromUtf8("checkBox_filterBadPulses"))
        self.horizontalLayout_6.addWidget(self.checkBox_filterBadPulses)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.checkBox_chopData = QtGui.QCheckBox(self.tab_generalsetup)
        self.checkBox_chopData.setObjectName(_fromUtf8("checkBox_chopData"))
        self.horizontalLayout_7.addWidget(self.checkBox_chopData)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 1, 0, 1, 1)
        self.tab_calibSetup.addTab(self.tab_generalsetup, _fromUtf8(""))
        self.tab_gsas = QtGui.QWidget()
        self.tab_gsas.setObjectName(_fromUtf8("tab_gsas"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_gsas)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_12 = QtGui.QLabel(self.tab_gsas)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_10.addWidget(self.label_12)
        self.lineEdit_gsasPRMFile = QtGui.QLineEdit(self.tab_gsas)
        self.lineEdit_gsasPRMFile.setObjectName(_fromUtf8("lineEdit_gsasPRMFile"))
        self.horizontalLayout_10.addWidget(self.lineEdit_gsasPRMFile)
        self.pushButton_gsasPRM = QtGui.QPushButton(self.tab_gsas)
        self.pushButton_gsasPRM.setObjectName(_fromUtf8("pushButton_gsasPRM"))
        self.horizontalLayout_10.addWidget(self.pushButton_gsasPRM)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem3)
        self.gridLayout_3.addLayout(self.horizontalLayout_10, 0, 0, 1, 1)
        self.tab_calibSetup.addTab(self.tab_gsas, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.radioButto_filterByTime = QtGui.QRadioButton(self.tab_2)
        self.radioButto_filterByTime.setText(_fromUtf8(""))
        self.radioButto_filterByTime.setObjectName(_fromUtf8("radioButto_filterByTime"))
        self.horizontalLayout_13.addWidget(self.radioButto_filterByTime)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem4)
        self.label_14 = QtGui.QLabel(self.tab_2)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_13.addWidget(self.label_14)
        self.lineEdit_filterStartTime = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_filterStartTime.setObjectName(_fromUtf8("lineEdit_filterStartTime"))
        self.horizontalLayout_13.addWidget(self.lineEdit_filterStartTime)
        self.label_15 = QtGui.QLabel(self.tab_2)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_13.addWidget(self.label_15)
        self.lineEdit_filterStopTime = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_filterStopTime.setObjectName(_fromUtf8("lineEdit_filterStopTime"))
        self.horizontalLayout_13.addWidget(self.lineEdit_filterStopTime)
        self.label_16 = QtGui.QLabel(self.tab_2)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_13.addWidget(self.label_16)
        self.lineEdit_filterTimeStep = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_filterTimeStep.setObjectName(_fromUtf8("lineEdit_filterTimeStep"))
        self.horizontalLayout_13.addWidget(self.lineEdit_filterTimeStep)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.line_2 = QtGui.QFrame(self.tab_2)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_3.addWidget(self.line_2)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.radioButton_filterByFile = QtGui.QRadioButton(self.tab_2)
        self.radioButton_filterByFile.setText(_fromUtf8(""))
        self.radioButton_filterByFile.setObjectName(_fromUtf8("radioButton_filterByFile"))
        self.horizontalLayout_14.addWidget(self.radioButton_filterByFile)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem6)
        self.label_21 = QtGui.QLabel(self.tab_2)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_14.addWidget(self.label_21)
        self.lineEdit_17 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_17.setObjectName(_fromUtf8("lineEdit_17"))
        self.horizontalLayout_14.addWidget(self.lineEdit_17)
        self.pushButton_9 = QtGui.QPushButton(self.tab_2)
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.horizontalLayout_14.addWidget(self.pushButton_9)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_14)
        self.line_3 = QtGui.QFrame(self.tab_2)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout_3.addWidget(self.line_3)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.radioButton_filterByLog = QtGui.QRadioButton(self.tab_2)
        self.radioButton_filterByLog.setText(_fromUtf8(""))
        self.radioButton_filterByLog.setObjectName(_fromUtf8("radioButton_filterByLog"))
        self.horizontalLayout_15.addWidget(self.radioButton_filterByLog)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem8)
        self.label_tabSampleLog = QtGui.QLabel(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_tabSampleLog.sizePolicy().hasHeightForWidth())
        self.label_tabSampleLog.setSizePolicy(sizePolicy)
        self.label_tabSampleLog.setMinimumSize(QtCore.QSize(20, 0))
        self.label_tabSampleLog.setObjectName(_fromUtf8("label_tabSampleLog"))
        self.horizontalLayout_15.addWidget(self.label_tabSampleLog)
        self.comboBox_sampleLogNames = QtGui.QComboBox(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_sampleLogNames.sizePolicy().hasHeightForWidth())
        self.comboBox_sampleLogNames.setSizePolicy(sizePolicy)
        self.comboBox_sampleLogNames.setObjectName(_fromUtf8("comboBox_sampleLogNames"))
        self.horizontalLayout_15.addWidget(self.comboBox_sampleLogNames)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem9)
        self.pushButton_eventFilterAssistant = QtGui.QPushButton(self.tab_2)
        self.pushButton_eventFilterAssistant.setObjectName(_fromUtf8("pushButton_eventFilterAssistant"))
        self.horizontalLayout_15.addWidget(self.pushButton_eventFilterAssistant)
        self.verticalLayout_3.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem10)
        self.label_19 = QtGui.QLabel(self.tab_2)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_16.addWidget(self.label_19)
        self.lineEdit_minLogValue = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_minLogValue.setObjectName(_fromUtf8("lineEdit_minLogValue"))
        self.horizontalLayout_16.addWidget(self.lineEdit_minLogValue)
        self.label_20 = QtGui.QLabel(self.tab_2)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_16.addWidget(self.label_20)
        self.lineEdit_maxLogValue = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_maxLogValue.setObjectName(_fromUtf8("lineEdit_maxLogValue"))
        self.horizontalLayout_16.addWidget(self.lineEdit_maxLogValue)
        self.label_18 = QtGui.QLabel(self.tab_2)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_16.addWidget(self.label_18)
        self.lineEdit_logValueStep = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_logValueStep.setObjectName(_fromUtf8("lineEdit_logValueStep"))
        self.horizontalLayout_16.addWidget(self.lineEdit_logValueStep)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem11)
        self.verticalLayout_3.addLayout(self.horizontalLayout_16)
        self.tab_calibSetup.addTab(self.tab_2, _fromUtf8(""))
        self.tab_debugSetup = QtGui.QWidget()
        self.tab_debugSetup.setObjectName(_fromUtf8("tab_debugSetup"))
        self.gridLayout_7 = QtGui.QGridLayout(self.tab_debugSetup)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_13 = QtGui.QLabel(self.tab_debugSetup)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_11.addWidget(self.label_13)
        self.lineEdit_baseDataPath = QtGui.QLineEdit(self.tab_debugSetup)
        self.lineEdit_baseDataPath.setObjectName(_fromUtf8("lineEdit_baseDataPath"))
        self.horizontalLayout_11.addWidget(self.lineEdit_baseDataPath)
        self.pushButton_browseBaseDataPath = QtGui.QPushButton(self.tab_debugSetup)
        self.pushButton_browseBaseDataPath.setObjectName(_fromUtf8("pushButton_browseBaseDataPath"))
        self.horizontalLayout_11.addWidget(self.pushButton_browseBaseDataPath)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem12)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.gridLayout_7.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.tab_calibSetup.addTab(self.tab_debugSetup, _fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.tab_calibSetup)
        self.gridLayout.addLayout(self.horizontalLayout_5, 7, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.line_5 = QtGui.QFrame(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_5.sizePolicy().hasHeightForWidth())
        self.line_5.setSizePolicy(sizePolicy)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.horizontalLayout_3.addWidget(self.line_5)
        self.label_SectionAddFiles = QtGui.QLabel(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_SectionAddFiles.sizePolicy().hasHeightForWidth())
        self.label_SectionAddFiles.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_SectionAddFiles.setFont(font)
        self.label_SectionAddFiles.setAlignment(QtCore.Qt.AlignCenter)
        self.label_SectionAddFiles.setObjectName(_fromUtf8("label_SectionAddFiles"))
        self.horizontalLayout_3.addWidget(self.label_SectionAddFiles)
        self.line_4 = QtGui.QFrame(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_4.sizePolicy().hasHeightForWidth())
        self.line_4.setSizePolicy(sizePolicy)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.horizontalLayout_3.addWidget(self.line_4)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_4 = QtGui.QLabel(Form)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_4.addWidget(self.label_4)
        self.lineEdit_nexusFile = QtGui.QLineEdit(Form)
        self.lineEdit_nexusFile.setObjectName(_fromUtf8("lineEdit_nexusFile"))
        self.horizontalLayout_4.addWidget(self.lineEdit_nexusFile)
        self.pushButton_browseNxsFile = QtGui.QPushButton(Form)
        self.pushButton_browseNxsFile.setObjectName(_fromUtf8("pushButton_browseNxsFile"))
        self.horizontalLayout_4.addWidget(self.pushButton_browseNxsFile)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem13)
        self.pushButton_addNxsFile = QtGui.QPushButton(Form)
        self.pushButton_addNxsFile.setObjectName(_fromUtf8("pushButton_addNxsFile"))
        self.horizontalLayout_4.addWidget(self.pushButton_addNxsFile)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem14)
        self.gridLayout.addLayout(self.horizontalLayout_4, 4, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(Form)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEdit_ipts = QtGui.QLineEdit(Form)
        self.lineEdit_ipts.setObjectName(_fromUtf8("lineEdit_ipts"))
        self.horizontalLayout_2.addWidget(self.lineEdit_ipts)
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_runstart = QtGui.QLineEdit(Form)
        self.lineEdit_runstart.setObjectName(_fromUtf8("lineEdit_runstart"))
        self.horizontalLayout_2.addWidget(self.lineEdit_runstart)
        self.label_3 = QtGui.QLabel(Form)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        self.lineEdit_runend = QtGui.QLineEdit(Form)
        self.lineEdit_runend.setObjectName(_fromUtf8("lineEdit_runend"))
        self.horizontalLayout_2.addWidget(self.lineEdit_runend)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem15)
        self.pushButton_addRuns = QtGui.QPushButton(Form)
        self.pushButton_addRuns.setObjectName(_fromUtf8("pushButton_addRuns"))
        self.horizontalLayout_2.addWidget(self.pushButton_addRuns)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem16)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_project = QtGui.QLabel(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(40)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_project.sizePolicy().hasHeightForWidth())
        self.label_project.setSizePolicy(sizePolicy)
        self.label_project.setObjectName(_fromUtf8("label_project"))
        self.horizontalLayout.addWidget(self.label_project)
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem17)
        self.comboBox_projectNames = QtGui.QComboBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(40)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_projectNames.sizePolicy().hasHeightForWidth())
        self.comboBox_projectNames.setSizePolicy(sizePolicy)
        self.comboBox_projectNames.setObjectName(_fromUtf8("comboBox_projectNames"))
        self.horizontalLayout.addWidget(self.comboBox_projectNames)
        spacerItem18 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem18)
        self.pushButton_selectproject = QtGui.QPushButton(Form)
        self.pushButton_selectproject.setObjectName(_fromUtf8("pushButton_selectproject"))
        self.horizontalLayout.addWidget(self.pushButton_selectproject)
        spacerItem19 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem19)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        spacerItem20 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout.addItem(spacerItem20, 1, 0, 1, 1)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        spacerItem21 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem21, 0, 0, 1, 1)
        spacerItem22 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem22, 0, 3, 1, 1)
        self.pushButton_reduceData = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_reduceData.sizePolicy().hasHeightForWidth())
        self.pushButton_reduceData.setSizePolicy(sizePolicy)
        self.pushButton_reduceData.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_reduceData.setFont(font)
        self.pushButton_reduceData.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_reduceData.setObjectName(_fromUtf8("pushButton_reduceData"))
        self.gridLayout_6.addWidget(self.pushButton_reduceData, 0, 2, 1, 1)
        self.checkBox_reduceinfo = QtGui.QCheckBox(Form)
        self.checkBox_reduceinfo.setObjectName(_fromUtf8("checkBox_reduceinfo"))
        self.gridLayout_6.addWidget(self.checkBox_reduceinfo, 0, 4, 1, 1)
        spacerItem23 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem23, 0, 5, 1, 1)
        spacerItem24 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem24, 0, 1, 1, 1)
        self.pushButton_quit = QtGui.QPushButton(Form)
        self.pushButton_quit.setObjectName(_fromUtf8("pushButton_quit"))
        self.gridLayout_6.addWidget(self.pushButton_quit, 0, 6, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_6, 9, 0, 1, 1)
        spacerItem25 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout.addItem(spacerItem25, 10, 0, 1, 1)

        self.retranslateUi(Form)
        self.tab_calibSetup.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.label_5.setText(_translate("Form", "Reduction Setup", None))
        self.label_8.setText(_translate("Form", "Vanadium Run", None))
        self.pushButton_timeFocusTableFile.setText(_translate("Form", "Browse", None))
        self.label_7.setToolTip(_translate("Form", "<html><head/><body><p>Vanadium Information file such as</p><p>&quot;/SNS/VULCAN/shared/Calibrationfiles/Instrument/Standard/Vanadium/VRecord.txt&quot;</p><p><br/></p><p>Used to look up vanadium run</p></body></html>", None))
        self.label_7.setText(_translate("Form", "Vanadium Database File", None))
        self.label_22.setText(_translate("Form", "Container Run", None))
        self.label_9.setText(_translate("Form", "Background Run", None))
        self.checkBox_autoVanRun.setText(_translate("Form", "Automatic Vanadium Run Search", None))
        self.pushButton_vanDBFile.setText(_translate("Form", "Browse", None))
        self.label_10.setText(_translate("Form", "Vanadium Background Run", None))
        self.label_6.setToolTip(_translate("Form", "<html><head/><body><p>Time focussing table file.  In PD, it was named as \'calibration file\'</p></body></html>", None))
        self.label_6.setText(_translate("Form", "Time Focusing Table", None))
        self.pushButton_vanDBCriteriaSetup.setToolTip(_translate("Form", "<html><head/><body><p>Launch a dialog box to set up criteria for search corresponding vanadium runs by vanadium database file</p></body></html>", None))
        self.pushButton_vanDBCriteriaSetup.setText(_translate("Form", "Criteria", None))
        self.tab_calibSetup.setTabText(self.tab_calibSetup.indexOf(self.tab_advsetup), _translate("Form", "Calibration Setup", None))
        self.label_11.setText(_translate("Form", "Bin Size", None))
        self.checkBox_sumRuns.setText(_translate("Form", "Sum Runs", None))
        self.checkBox_filterBadPulses.setText(_translate("Form", "Filter Bad Pulses", None))
        self.checkBox_chopData.setText(_translate("Form", "Chop Data", None))
        self.tab_calibSetup.setTabText(self.tab_calibSetup.indexOf(self.tab_generalsetup), _translate("Form", "General Setup", None))
        self.label_12.setText(_translate("Form", "GSAS Instrument File", None))
        self.pushButton_gsasPRM.setText(_translate("Form", "Bowse", None))
        self.tab_calibSetup.setTabText(self.tab_calibSetup.indexOf(self.tab_gsas), _translate("Form", "GSAS", None))
        self.label_14.setText(_translate("Form", "Start Time", None))
        self.label_15.setText(_translate("Form", "Stop Time", None))
        self.label_16.setText(_translate("Form", "Time Step", None))
        self.label_21.setToolTip(_translate("Form", "<html><head/><body><p>User defined time chopping file</p></body></html>", None))
        self.label_21.setText(_translate("Form", "Pick Time File", None))
        self.pushButton_9.setText(_translate("Form", "Browse", None))
        self.label_tabSampleLog.setText(_translate("Form", "Sample Log", None))
        self.pushButton_eventFilterAssistant.setText(_translate("Form", "Event Filtering Assistant", None))
        self.label_19.setText(_translate("Form", "Min Value", None))
        self.label_20.setText(_translate("Form", "Max Value", None))
        self.label_18.setText(_translate("Form", "Step", None))
        self.tab_calibSetup.setTabText(self.tab_calibSetup.indexOf(self.tab_2), _translate("Form", "Chop Data", None))
        self.label_13.setText(_translate("Form", "Base Data Path", None))
        self.pushButton_browseBaseDataPath.setText(_translate("Form", "Browse", None))
        self.tab_calibSetup.setTabText(self.tab_calibSetup.indexOf(self.tab_debugSetup), _translate("Form", "Debug Setup", None))
        self.label_SectionAddFiles.setText(_translate("Form", "Add Files", None))
        self.label_4.setText(_translate("Form", "NeXus File", None))
        self.pushButton_browseNxsFile.setText(_translate("Form", "Browse", None))
        self.pushButton_addNxsFile.setText(_translate("Form", "Add", None))
        self.label.setText(_translate("Form", "IPTS", None))
        self.label_2.setText(_translate("Form", "First Run", None))
        self.label_3.setText(_translate("Form", "Last Run", None))
        self.pushButton_addRuns.setText(_translate("Form", "Add", None))
        self.label_project.setText(_translate("Form", "Project", None))
        self.pushButton_selectproject.setText(_translate("Form", "Select", None))
        self.pushButton_reduceData.setText(_translate("Form", "Reduce", None))
        self.checkBox_reduceinfo.setText(_translate("Form", "See Info", None))
        self.pushButton_quit.setText(_translate("Form", "Quit", None))

