# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ReductionSetup.ui'
#
# Created: Fri Jan 30 10:44:30 2015
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1013, 771)
        self.lineEdit_runstart = QtGui.QLineEdit(Form)
        self.lineEdit_runstart.setGeometry(QtCore.QRect(320, 80, 113, 27))
        self.lineEdit_runstart.setObjectName(_fromUtf8("lineEdit_runstart"))
        self.lineEdit_runend = QtGui.QLineEdit(Form)
        self.lineEdit_runend.setGeometry(QtCore.QRect(550, 80, 113, 27))
        self.lineEdit_runend.setObjectName(_fromUtf8("lineEdit_runend"))
        self.lineEdit_ipts = QtGui.QLineEdit(Form)
        self.lineEdit_ipts.setGeometry(QtCore.QRect(130, 80, 113, 27))
        self.lineEdit_ipts.setObjectName(_fromUtf8("lineEdit_ipts"))
        self.label = QtGui.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(50, 80, 41, 17))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(250, 80, 71, 17))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(470, 80, 66, 17))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.pushButton = QtGui.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(760, 150, 98, 27))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.checkBox = QtGui.QCheckBox(Form)
        self.checkBox.setGeometry(QtCore.QRect(550, 270, 97, 22))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.label_4 = QtGui.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(40, 150, 81, 17))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.lineEdit = QtGui.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(130, 150, 381, 27))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.pushButton_2 = QtGui.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(560, 150, 98, 27))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.pushButton_3 = QtGui.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(760, 80, 98, 27))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.comboBox = QtGui.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(130, 20, 301, 27))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.label_5 = QtGui.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(40, 20, 66, 17))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.pushButton_4 = QtGui.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(470, 20, 98, 27))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.line = QtGui.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(20, 220, 971, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.tab_setup = QtGui.QTabWidget(Form)
        self.tab_setup.setGeometry(QtCore.QRect(30, 340, 921, 401))
        self.tab_setup.setObjectName(_fromUtf8("tab_setup"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.lineEdit_2 = QtGui.QLineEdit(self.tab)
        self.lineEdit_2.setGeometry(QtCore.QRect(190, 30, 361, 27))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(20, 30, 111, 17))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.pushButton_5 = QtGui.QPushButton(self.tab)
        self.pushButton_5.setGeometry(QtCore.QRect(610, 30, 98, 27))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.label_7 = QtGui.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(20, 100, 161, 17))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.lineEdit_3 = QtGui.QLineEdit(self.tab)
        self.lineEdit_3.setGeometry(QtCore.QRect(190, 100, 361, 27))
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.label_8 = QtGui.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(30, 180, 111, 17))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(420, 250, 131, 17))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(420, 180, 191, 17))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.pushButton_6 = QtGui.QPushButton(self.tab)
        self.pushButton_6.setGeometry(QtCore.QRect(610, 100, 98, 27))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.lineEdit_4 = QtGui.QLineEdit(self.tab)
        self.lineEdit_4.setGeometry(QtCore.QRect(190, 170, 113, 27))
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.lineEdit_5 = QtGui.QLineEdit(self.tab)
        self.lineEdit_5.setGeometry(QtCore.QRect(580, 240, 113, 27))
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.lineEdit_6 = QtGui.QLineEdit(self.tab)
        self.lineEdit_6.setGeometry(QtCore.QRect(650, 180, 113, 27))
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.label_22 = QtGui.QLabel(self.tab)
        self.label_22.setGeometry(QtCore.QRect(30, 240, 111, 17))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.lineEdit_16 = QtGui.QLineEdit(self.tab)
        self.lineEdit_16.setGeometry(QtCore.QRect(180, 240, 113, 27))
        self.lineEdit_16.setObjectName(_fromUtf8("lineEdit_16"))
        self.tab_setup.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.lineEdit_8 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_8.setGeometry(QtCore.QRect(80, 20, 271, 27))
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.label_12 = QtGui.QLabel(self.tab_2)
        self.label_12.setGeometry(QtCore.QRect(10, 30, 66, 17))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.tab_2)
        self.label_13.setGeometry(QtCore.QRect(10, 70, 41, 17))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.lineEdit_9 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_9.setGeometry(QtCore.QRect(80, 70, 113, 27))
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.pushButton_7 = QtGui.QPushButton(self.tab_2)
        self.pushButton_7.setGeometry(QtCore.QRect(410, 20, 91, 71))
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.pushButton_8 = QtGui.QPushButton(self.tab_2)
        self.pushButton_8.setGeometry(QtCore.QRect(250, 70, 98, 27))
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.comboBox_2 = QtGui.QComboBox(self.tab_2)
        self.comboBox_2.setGeometry(QtCore.QRect(560, 20, 301, 31))
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.pushButton_9 = QtGui.QPushButton(self.tab_2)
        self.pushButton_9.setGeometry(QtCore.QRect(560, 70, 98, 27))
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.lineEdit_10 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_10.setGeometry(QtCore.QRect(110, 190, 191, 27))
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.lineEdit_11 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_11.setGeometry(QtCore.QRect(390, 190, 191, 27))
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.lineEdit_12 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_12.setGeometry(QtCore.QRect(690, 190, 191, 27))
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.label_14 = QtGui.QLabel(self.tab_2)
        self.label_14.setGeometry(QtCore.QRect(10, 190, 71, 17))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(self.tab_2)
        self.label_15.setGeometry(QtCore.QRect(310, 190, 71, 17))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(self.tab_2)
        self.label_16.setGeometry(QtCore.QRect(600, 190, 71, 17))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_17 = QtGui.QLabel(self.tab_2)
        self.label_17.setGeometry(QtCore.QRect(10, 260, 81, 17))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.comboBox_3 = QtGui.QComboBox(self.tab_2)
        self.comboBox_3.setGeometry(QtCore.QRect(110, 260, 191, 27))
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.line_2 = QtGui.QFrame(self.tab_2)
        self.line_2.setGeometry(QtCore.QRect(0, 130, 921, 21))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.label_18 = QtGui.QLabel(self.tab_2)
        self.label_18.setGeometry(QtCore.QRect(310, 310, 71, 17))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.lineEdit_13 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_13.setGeometry(QtCore.QRect(390, 310, 191, 27))
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.lineEdit_14 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_14.setGeometry(QtCore.QRect(690, 310, 191, 27))
        self.lineEdit_14.setObjectName(_fromUtf8("lineEdit_14"))
        self.lineEdit_15 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_15.setGeometry(QtCore.QRect(110, 310, 191, 27))
        self.lineEdit_15.setObjectName(_fromUtf8("lineEdit_15"))
        self.label_19 = QtGui.QLabel(self.tab_2)
        self.label_19.setGeometry(QtCore.QRect(10, 310, 71, 17))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_20 = QtGui.QLabel(self.tab_2)
        self.label_20.setGeometry(QtCore.QRect(600, 310, 71, 17))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_21 = QtGui.QLabel(self.tab_2)
        self.label_21.setGeometry(QtCore.QRect(680, 80, 191, 17))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.tab_setup.addTab(self.tab_2, _fromUtf8(""))
        self.lineEdit_7 = QtGui.QLineEdit(Form)
        self.lineEdit_7.setGeometry(QtCore.QRect(130, 260, 171, 27))
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.label_11 = QtGui.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(30, 260, 71, 17))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.checkBox_2 = QtGui.QCheckBox(Form)
        self.checkBox_2.setGeometry(QtCore.QRect(400, 270, 97, 22))
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.checkBox_3 = QtGui.QCheckBox(Form)
        self.checkBox_3.setGeometry(QtCore.QRect(700, 270, 141, 22))
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))

        self.retranslateUi(Form)
        self.tab_setup.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.label.setText(_translate("Form", "IPTS", None))
        self.label_2.setText(_translate("Form", "First Run", None))
        self.label_3.setText(_translate("Form", "Last Run", None))
        self.pushButton.setText(_translate("Form", "Add", None))
        self.checkBox.setText(_translate("Form", "Sum Runs", None))
        self.label_4.setText(_translate("Form", "NeXus File", None))
        self.pushButton_2.setText(_translate("Form", "Browse", None))
        self.pushButton_3.setText(_translate("Form", "Add", None))
        self.label_5.setText(_translate("Form", "Project", None))
        self.pushButton_4.setText(_translate("Form", "Select", None))
        self.label_6.setText(_translate("Form", "Calibration File", None))
        self.pushButton_5.setText(_translate("Form", "Browse", None))
        self.label_7.setText(_translate("Form", "Characterization File", None))
        self.label_8.setText(_translate("Form", "Vanadium Run", None))
        self.label_9.setText(_translate("Form", "Background Run", None))
        self.label_10.setText(_translate("Form", "Vanadium Background Run", None))
        self.pushButton_6.setText(_translate("Form", "Browse", None))
        self.label_22.setText(_translate("Form", "Container Run", None))
        self.tab_setup.setTabText(self.tab_setup.indexOf(self.tab), _translate("Form", "Setup", None))
        self.label_12.setText(_translate("Form", "Run", None))
        self.label_13.setText(_translate("Form", "File", None))
        self.pushButton_7.setText(_translate("Form", "Load", None))
        self.pushButton_8.setText(_translate("Form", "Browse", None))
        self.pushButton_9.setText(_translate("Form", "Plot", None))
        self.label_14.setText(_translate("Form", "Start Time", None))
        self.label_15.setText(_translate("Form", "Stop Time", None))
        self.label_16.setText(_translate("Form", "Time Step", None))
        self.label_17.setText(_translate("Form", "Sample Log", None))
        self.label_18.setText(_translate("Form", "Step", None))
        self.label_19.setText(_translate("Form", "Min Value", None))
        self.label_20.setText(_translate("Form", "Max Value", None))
        self.label_21.setText(_translate("Form", "----> Launch anothe window for ", None))
        self.tab_setup.setTabText(self.tab_setup.indexOf(self.tab_2), _translate("Form", "Chop Data", None))
        self.label_11.setText(_translate("Form", "Bin Size", None))
        self.checkBox_2.setText(_translate("Form", "Chop Data", None))
        self.checkBox_3.setText(_translate("Form", "Filter Bad Pulses", None))

